#!/usr/bin/perl
use strict;
use warnings;
use Getopt::Long;
use Pod::Usage;
use Data::Dumper;
use JSON::XS;
use YAML::Any;

my %params;

sub main {
    my $cachefilename = "$ENV{HOME}/.ec2connect";
    my $awscommand = "aws ";
    my $awsgetec2list;
    my @ec2list;
    my $instanceid;
    my $launchtime;
    my ($config);
    my $configfile = "$ENV{HOME}/.ec2connect.config";

    my $result = GetOptions (
	"name|n=s"         => \$params{name},
	"type|t=s"         => \$params{type},
	"nocache"          => \$params{nocache},
	"profile|p=s"      => \$params{profile},
	"region|r=s"       => \$params{region},
	"list|l"           => \$params{list},
	"help|h"           => \$params{help},
	"verbose|v"        => \$params{verbose},
	"man|m"            => \$params{man},
	"bash_completion"  => \$params{bash_completion}
       );

    if ( $params{bash_completion }) {
	bash_completion();
    }

    if ( $params{man} ) {
	pod2usage( -verbose => 2 );
    }

    if ( -s $configfile ) {
	$config = YAML::Any::LoadFile( "$configfile" ) || pod2usage( { -message => "cannot open $configfile", -verbose => 1, -exitval => 2} );
    }

    if ( ! ( $params{name} || $params{type} || $params{list} ) || $params{help} ) {
        pod2usage(1);
    }

    if ( ! $params{profile} && $params{name} ) {
	for my $i ( 0 .. $#{$config->{hosts}}) {
	    if ( $params{name} eq ${${$config->{hosts}}[$i]}{alias} ) {
		$params{profile} = ${${$config->{hosts}}[$i]}{profile};
		$params{region} = ${${$config->{hosts}}[$i]}{region};
		$params{name} = ${${$config->{hosts}}[$i]}{name};
	    }
	}
    }

    if ( ! $params{profile} ) {
	if ( $config->{defaults}->{profile}) {
	    $params{profile} = $config->{defaults}->{profile};
	}
    }

    if ( ! $params{profile} ) {
	$cachefilename = $cachefilename . "_default";
    }
    else {
	$cachefilename = $cachefilename . "_" . $params{profile};
	$awscommand = $awscommand . " --profile $params{profile}";
    }

    if ( ! $params{region} ) {
	if ( $config->{defaults}->{region}) {
	    $params{region} = $config->{defaults}->{region};
	}
    }

    if ( ! $params{region} ) {
	$cachefilename = $cachefilename . "_default.cache";
    }
    else {
	$cachefilename = $cachefilename . "_" . $params{region} . ".cache";
	$awscommand = $awscommand . " --region $params{region}";
    }

    if (  -s $cachefilename && -M $cachefilename < 1  && ! $params{nocache}) {
	open (FILE, "< $cachefilename") or die "can't open $cachefilename: $!";
	undef $/;		# read in file all at once;
	eval <FILE>;
	die "can't recreate cache from $cachefilename: $@" if $@;
	close FILE;
    }
    else {
	print STDERR "fetching list....\n";
	$awsgetec2list = $awscommand . " ec2 describe-instances --query 'Reservations[].Instances[].[InstanceId,Tags[?Key==`Name`].Value[] | [0],Tags[?Key==`Type`].Value[] | [0],LaunchTime]' --filters Name=instance-state-name,Values=pending,running,shutting-down,stopping,stopped --output json";
	my $result = `$awsgetec2list`;
	@ec2list = decode_json $result;
	$Data::Dumper::Purity = 1;
	open (FILE, "> $cachefilename") or die "can't open $cachefilename: $!";
	print FILE Data::Dumper->Dump([\@ec2list], ['*ec2list']);
	close FILE                       or die "can't close $cachefilename: $!";
    }

    if ( $params{list} ) {
	for my $i ( 0 .. $#{$ec2list[0]} ) {
	    if ( ${$ec2list[0]}[$i][1] ) {
		printf("%-55s", ${$ec2list[0]}[$i][1]);
	    } else {
		printf("%-55s", ${$ec2list[0]}[$i][0]);
	    }
	    print "\t${$ec2list[0]}[$i][3]";
	    if ( ${$ec2list[0]}[$i][2] ) {
		print "\t" . ${$ec2list[0]}[$i][2] . "\n";
	    } else {
	       print "\n";
	    }
	}
	exit 0;
    }

    if ( $params{name}) {
	for my $i ( 0 .. $#{$ec2list[0]} ) {
	    if ( ${$ec2list[0]}[$i][1] && ${$ec2list[0]}[$i][1] eq $params{name} ) {
		$instanceid = ${$ec2list[0]}[$i][0];
		$launchtime = ${$ec2list[0]}[$i][3];
		last;
	    } elsif ( ${$ec2list[0]}[$i][0] eq $params{name} ) {
		# search for ids instead as we didn't found a name tag match.
		$instanceid = ${$ec2list[0]}[$i][0];
		$launchtime = ${$ec2list[0]}[$i][3];
		last;
	    }

	}
    } elsif ( $params{type} ) {
	my $typecount = 0;
	for my $i ( 0 .. $#{$ec2list[0]} ) {
	    if ( ${$ec2list[0]}[$i][2] && ${$ec2list[0]}[$i][2] eq $params{type} ) {
		$typecount++;
	    }
	}
	my $node = int(rand($typecount+1));
	$instanceid = ${$ec2list[0]}[$node][0];
	$launchtime = ${$ec2list[0]}[$node][3];
    } else {
	exit 0;
    }

    if ( $instanceid ) {
	print STDERR ($params{profile} || "default" ) . " - " . ($params{region} || "default" ) . " - " . $instanceid . " - " . $launchtime . "\n";
	system("$awscommand ssm start-session --target ${instanceid}");
    }
}

sub bash_completion {
    print '
__ec2connect_completions()
{
  local cur prev words cword
  _init_completion -n : || return

  local ipvx

  COMPREPLY=()   # Array variable storing the possible completions.
  cur=${COMP_WORDS[COMP_CWORD]}

  case "$cur" in
    *)
    COMPREPLY=( $( compgen -W \'-n -p -r -l -h -m \
                               --name --profile --region --help \' -- $cur ) );;
  esac

  case $prev in
    --region|-r)
      AWS_PROFILE=$(echo -n ${COMP_LINE} | grep --color=never -Poe \'-(-profile|p) \K[^ ]*\')

      if [ -n "${AWS_PROFILE}" ]; then
          COMPREPLY=( $( compgen -W "$(command aws --profile=${AWS_PROFILE} ec2 describe-regions --query "Regions[].{Name:RegionName}" --output text)" -- $cur) )
      else
          COMPREPLY=( $( compgen -W "$(command aws ec2 describe-regions --query "Regions[].{Name:RegionName}" --output text)" -- $cur) )
      fi
      ;;

    --profile|-p)
      COMPREPLY=($(compgen -W "$(command aws configure list-profiles)" -- $cur))
      ;;

    --name|-n)
      AWS_PROFILE=$(echo -n ${COMP_LINE} | grep --color=never -Poe \'-(-profile|p) \K[^ ]*\')
      AWS_REGION=$(echo -n ${COMP_LINE} | grep --color=never -Poe \'-(-region|r) \K[^ ]*\')

      if [ -n "${AWS_PROFILE}" ] && [ -n "${AWS_REGION}" ]; then
        COMPREPLY=( $( compgen -W "$(command $COMP_WORDS --profile ${AWS_PROFILE} --region ${AWS_REGION} -l | awk -F\'\t\' \'{print $1}\')" -- $cur ))
      elif [ -n "${AWS_PROFILE}" ]; then

        COMPREPLY=( $( compgen -W "$(command $COMP_WORDS --profile ${AWS_PROFILE} -l | awk -F\'\t\' \'{print $1}\')" -- $cur ))
      elif [ -n "${AWS_REGION}" ]; then
        COMPREPLY=( $( compgen -W "$(command $COMP_WORDS --region ${AWS_REGION} -l | awk -F\'\t\' \'{print $1}\')" -- $cur ))
      else
        COMPREPLY=( $( compgen -W "$(command $COMP_WORDS -l | awk -F\'\t\' \'{print $1}\')" -- $cur ))

      fi
     ;;

    --type|-t)
      AWS_PROFILE=$(echo -n ${COMP_LINE} | grep --color=never -Poe \'-(-profile|p) \K[^ ]*\')
      AWS_REGION=$(echo -n ${COMP_LINE} | grep --color=never -Poe \'-(-region|r) \K[^ ]*\')

      if [ -n "${AWS_PROFILE}" ] && [ -n "${AWS_REGION}" ]; then
        COMPREPLY=( $( compgen -W "$(command $COMP_WORDS --profile ${AWS_PROFILE} --region ${AWS_REGION} -l | awk -F\'\t\' \'{print $3}\')" -- $cur ))
      elif [ -n "${AWS_PROFILE}" ]; then

        COMPREPLY=( $( compgen -W "$(command $COMP_WORDS --profile ${AWS_PROFILE} -l | awk -F\'\t\' \'{print $3}\')" -- $cur ))
      elif [ -n "${AWS_REGION}" ]; then
        COMPREPLY=( $( compgen -W "$(command $COMP_WORDS --region ${AWS_REGION} -l | awk -F\'\t\' \'{print $3}\')" -- $cur ))
      else
        COMPREPLY=( $( compgen -W "$(command $COMP_WORDS -l | awk -F\'\t\' \'{print $3}\')" -- $cur ))

      fi
     ;;
  esac

  return 0
}

complete -F __ec2connect_completions ec2-connect
';
    exit 0;

}

main();

1;

__END__

=head1 NAME

ec2-connect.pl - connect to aws ec2 instances via ssm

=head1 DESCRIPTION

Just a wrapper around aws ssm command to connect by using Name tags.

=head1 SYNOPSIS

ec2-connect

Options:

  --help, -h     for help
  --man, -m      for man page
  --nocache      ignore local cache file
  --profile, -p  aws profile to use
  --region, -r   aws region to use
  --list, -l     list Name tags
  --name, -n     instance name Tag to connect to.
  --type, -t     instance type to connect to.
  --bash_completion use as source <(ec2-connect --bash_completion) in bashrc.

=cut

=head1 AUTHOR

Andreas Gerler <baron@bundesbrandschatzamt.de>

=head1 LICENSE

This program is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
